"""initial_screenshot_help"""

import sqlalchemy as sa
from alembic import op

revision = "ffc3f8107658"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("locale", sa.String(), nullable=False),
        sa.Column("privacy_notice_version", sa.String(), nullable=False),
        sa.Column("analytics_opt_in", sa.Boolean(), nullable=False),
        sa.Column("auth_revoked_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deletion_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deletion_jobs",
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("online_purge_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("backup_expiry_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "resource_id"),
    )
    op.create_index(op.f("ix_deletion_jobs_owner_id"), "deletion_jobs", ["owner_id"], unique=False)
    op.create_table(
        "guidance_events",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("control_epoch", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence"),
    )
    op.create_index(
        op.f("ix_guidance_events_expires_at"), "guidance_events", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_guidance_events_owner_id"), "guidance_events", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_guidance_events_session_id"), "guidance_events", ["session_id"], unique=False
    )
    op.create_table(
        "guide_tasks",
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("goal", sa.String(length=4000), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("application_key", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_session_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index(op.f("ix_guide_tasks_expires_at"), "guide_tasks", ["expires_at"], unique=False)
    op.create_index(op.f("ix_guide_tasks_owner_id"), "guide_tasks", ["owner_id"], unique=False)
    op.create_table(
        "idempotency_records",
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("route", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("request_digest", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_ref", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "method", "route", "key"),
    )
    op.create_index(
        op.f("ix_idempotency_records_expires_at"),
        "idempotency_records",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_idempotency_records_owner_id"), "idempotency_records", ["owner_id"], unique=False
    )
    op.create_table(
        "guide_sessions",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("previous_session_id", sa.String(length=36), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=False),
        sa.Column("control_epoch", sa.BigInteger(), nullable=False),
        sa.Column("checkpoint_state", sa.String(), nullable=True),
        sa.Column("current_step_id", sa.String(), nullable=True),
        sa.Column("confirmed_plan_version", sa.Integer(), nullable=True),
        sa.Column("controller_device_id", sa.String(), nullable=True),
        sa.Column("observation_mode", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=True),
        sa.Column("last_user_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id", "task_id"],
            ["guide_tasks.owner_id", "guide_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
        sa.UniqueConstraint("owner_id", "task_id", "id"),
    )
    op.create_index(
        op.f("ix_guide_sessions_expires_at"), "guide_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_guide_sessions_owner_id"), "guide_sessions", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_guide_sessions_task_id"), "guide_sessions", ["task_id"], unique=False)
    op.create_table(
        "analysis_results",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("observations", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.String(length=4000), nullable=False),
        sa.Column("needs_context", sa.Boolean(), nullable=False),
        sa.Column("context_request", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id", "task_id", "session_id"],
            ["guide_sessions.owner_id", "guide_sessions.task_id", "guide_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index(
        op.f("ix_analysis_results_expires_at"), "analysis_results", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_results_owner_id"), "analysis_results", ["owner_id"], unique=False
    )
    op.create_table(
        "operations",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("expected_state_version", sa.Integer(), nullable=False),
        sa.Column("control_epoch", sa.Integer(), nullable=False),
        sa.Column("request_digest", sa.String(), nullable=False),
        sa.Column("result_ref", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id", "task_id", "session_id"],
            ["guide_sessions.owner_id", "guide_sessions.task_id", "guide_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index(op.f("ix_operations_expires_at"), "operations", ["expires_at"], unique=False)
    op.create_index(op.f("ix_operations_owner_id"), "operations", ["owner_id"], unique=False)
    op.create_index(op.f("ix_operations_status"), "operations", ["status"], unique=False)
    op.create_table(
        "screenshots",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("replaces_screenshot_id", sa.String(), nullable=True),
        sa.Column("redaction_version", sa.String(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id", "task_id", "session_id"],
            ["guide_sessions.owner_id", "guide_sessions.task_id", "guide_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "task_id"],
            ["guide_tasks.owner_id", "guide_tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "id"),
    )
    op.create_index(op.f("ix_screenshots_expires_at"), "screenshots", ["expires_at"], unique=False)
    op.create_index(op.f("ix_screenshots_owner_id"), "screenshots", ["owner_id"], unique=False)
    op.create_index(op.f("ix_screenshots_session_id"), "screenshots", ["session_id"], unique=False)
    op.create_index(op.f("ix_screenshots_task_id"), "screenshots", ["task_id"], unique=False)
    op.create_table(
        "operation_evidence",
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("screenshot_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id", "operation_id"],
            ["operations.owner_id", "operations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id", "screenshot_id"],
            ["screenshots.owner_id", "screenshots.id"],
        ),
        sa.PrimaryKeyConstraint("operation_id", "screenshot_id"),
    )
    op.create_index(
        op.f("ix_operation_evidence_screenshot_id"),
        "operation_evidence",
        ["screenshot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operation_evidence_screenshot_id"), table_name="operation_evidence")
    op.drop_table("operation_evidence")
    op.drop_index(op.f("ix_screenshots_task_id"), table_name="screenshots")
    op.drop_index(op.f("ix_screenshots_session_id"), table_name="screenshots")
    op.drop_index(op.f("ix_screenshots_owner_id"), table_name="screenshots")
    op.drop_index(op.f("ix_screenshots_expires_at"), table_name="screenshots")
    op.drop_table("screenshots")
    op.drop_index(op.f("ix_operations_status"), table_name="operations")
    op.drop_index(op.f("ix_operations_owner_id"), table_name="operations")
    op.drop_index(op.f("ix_operations_expires_at"), table_name="operations")
    op.drop_table("operations")
    op.drop_index(op.f("ix_analysis_results_owner_id"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_expires_at"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_guide_sessions_task_id"), table_name="guide_sessions")
    op.drop_index(op.f("ix_guide_sessions_owner_id"), table_name="guide_sessions")
    op.drop_index(op.f("ix_guide_sessions_expires_at"), table_name="guide_sessions")
    op.drop_table("guide_sessions")
    op.drop_index(op.f("ix_idempotency_records_owner_id"), table_name="idempotency_records")
    op.drop_index(op.f("ix_idempotency_records_expires_at"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_guide_tasks_owner_id"), table_name="guide_tasks")
    op.drop_index(op.f("ix_guide_tasks_expires_at"), table_name="guide_tasks")
    op.drop_table("guide_tasks")
    op.drop_index(op.f("ix_guidance_events_session_id"), table_name="guidance_events")
    op.drop_index(op.f("ix_guidance_events_owner_id"), table_name="guidance_events")
    op.drop_index(op.f("ix_guidance_events_expires_at"), table_name="guidance_events")
    op.drop_table("guidance_events")
    op.drop_index(op.f("ix_deletion_jobs_owner_id"), table_name="deletion_jobs")
    op.drop_table("deletion_jobs")
    op.drop_table("users")
    # ### end Alembic commands ###
